general.import = [
  "~/.config/alacritty/themes/classic.toml"
]

[window]

opacity = 0.9

padding.x = 10
padding.y = 10

decorations = "Transparent"
decorations_theme_variant = "Dark" # "Dark"

[cursor]

style = "Beam"

[font]

normal = { family = "IBM Plex Mono", style = "Regular" }
bold = { family = "IBM Plex Mono", style = "Bold" }
italic = { family = "IBM Plex Mono", style = "Italic" }
bold_italic = { family = "IBM Plex Mono", style = "Bold Italic" }

# normal = { family = "IosevkaTerm Nerd Font", style = "Regular" }
# bold = { family = "IosevkaTerm Nerd Font", style = "Heavy" }
# italic = { family = "IosevkaTerm Nerd Font", style = "Heavy Oblique" }
# bold_italic = { family = "IosevkaTerm Nerd Font", style = "Medium Oblique" }

# normal = { family = "JetBrains Mono Nerd Font", style = "Regular" }
# bold = { family = "JetBrains Mono Nerd Font", style = "Bold" }
# italic = { family = "JetBrains Mono Nerd Font", style = "Italic" }
# bold_italic = { family = "JetBrains Mono Nerd Font", style = "Bold Italic" }
size = 12
