#! /bin/sh

xrandr --output HDMI-1-2 --auto --rotate right --output HDMI-3 --primary --output HDMI-1-2 --right-of HDMI-3

setxkbmap es

pgrep -x sxhkd > /dev/null || sxhkd &

compfy &

nm-applet &

flameshot &

nitrogen --restore &

bspc monitor HDMI-3 -d I II III IV V  
bspc monitor HDMI-1-2 -d VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          12

bspc config focused_border_color "#b3ec3d"
bspc config normal_border_color "#242424"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

sleep 1

$HOME/.config/polybar/launch.sh

pulseaudio -k
pulseaudio --start
