#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh

nitrogen --restore &

picom -f &

bspc monitor -d I II III IV V 

bspc config border_width         2

bspc config focused_border_color "#FAFAFA"  # Color del borde de la ventana activa
bspc config normal_border_color "#747272" 

bspc config window_gap           30

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Brave state=tiled
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Configuración del cursor
xsetroot -cursor_name left_ptr
